### ISSUE TITLE
compare frozen selection

### ISSUE THREAD

**Issue by Maxiveri** [Irrational-Encoding-Wizardry/yuuno#31]
* yuuno version: 0.6.0
* Python version: 3.6.2
* Operating System: Windows 10 Pro 64-bit

### Description

I was trying to use the `%compare` function of yuuno.

The expected behaviour is to be able to switch between the diffrent clips with a visual indicator that clip No. X is selected.

What happened is that I can switch between the clips, besides the first one and without a visiual indicator on which clip is curretly selected.

In the Zip (pw=yUUno) there is a video recording of this Issue and also the notebook and my sourcefile.

### What I Did

```
from vapoursynth import core
import mvsfunc as mvf
src1 = core.ffms2.Source("C:\\Users\Max\\bladedance_grain_src.png")
src1 = src1 * 30
src1 = mvf.ToYUV(src1)

g1 = src1.grain.Add(var=9000, hcorr=0.5, vcorr=0.5)

%compare src1, g1, src1, g1, src1
```
I can this issue in Chrome, Firefox and Edge. I rezised the width of the jupyter notebook to have a better fit with my monitor width.
[mwe.zip](https://github.com/Irrational-Encoding-Wizardry/yuuno/files/1285565/mwe.zip)

**Comment by stuxcrystal** [comment]
I cannot reproduce this issue.

Maybe you didn't notice that the kernel may have been busy at the time you were clicking the buttons.
Please make sure the circle at the top-right corner besides the "Python 3" is not filled. The circle being filled means that the kernel is currently executing stuff and all other commands have to wait.

**Comment by Maxiveri** [comment]
Force installed an older version of ipywidgets via
`pip install ipywidgets==6.0.0`

It's now working for me. If I upgrade it via
`pip install -U ipywidgets`

the same behaviour can be seen.

**Comment by stuxcrystal** [comment]
I added `ipywidgets<7` to the requirements as a workaround.

**Comment by stuxcrystal** [comment]
Closed. As widgets have been rewritten.
