### ISSUE TITLE
Installation via pip fails on Windows - No module named '_pyrsistent_version'

### ISSUE THREAD

**Issue by theChaosCoder** [Irrational-Encoding-Wizardry/yuuno#33]
* yuuno version: 1.2
* Python version: 3.7.4
* Operating System: Windows x64 1903

### Description
Can't install via pip 19.1.1. It shows the following error:
```
Using cached https://files.pythonhosted.org/packages/6c/ef/7781092174a42d0b57fb02a2eb23f78ebc8e588c9bd7455e1d1c7b1ea516/pyrsistent-0.15.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bob\AppData\Local\Temp\pip-install-7p2t7jfe\pyrsistent\setup.py", line 10, in <module>
        from _pyrsistent_version import __version__
    ModuleNotFoundError: No module named '_pyrsistent_version'

    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\bob\AppData\Local\Temp\pip-install-7p2t7jfe\pyrsistent\
```
### What I Did

```
.\python.exe -m pip install yuuno
```

**Comment by stuxcrystal** [comment]
It seems something with you pip-download failed.

Can you try to install yuuno using `python -m pip install --no-cache-dir yuuno` and tell me if the problem persists?

**Comment by theChaosCoder** [comment]
Nope doesn't help. I even tried it in a clean VM.

**Comment by theChaosCoder** [comment]
I forgot to mention that I used the "python embedded version". It installs fine with the regular version.

**Comment by stuxcrystal** [comment]
Can you tell me how you installed the embedded version so I can try to reproduce the error?

**Comment by theChaosCoder** [comment]
You just "install" pip via get-pip.py while calling your local python.exe
See here https://github.com/theChaosCoder/vapoursynth-portable-FATPACK/blob/master/build.ps1
