### ISSUE TITLE
How can I use it with VapourSynth64Portable on the win?

### ISSUE THREAD

**Issue by hujingyu216** [Irrational-Encoding-Wizardry/yuuno#34]
* yuuno version:VapourSynth64Portable
* Python version:
* Operating System:win10

### Description
How can I use it with VapourSynth64Portable on the win?
I

**Comment by stuxcrystal** [comment]
### Short answer:
If `import vapoursynth` works, and `%load_ext yuuno` works, you are set up.

### Short answer for experts:
As long as `vapoursynth` is on `sys.path`, Yuuno will work.

### What does this mean?
There are multiple ways to ensure `vapoursynth` is on `sys.path`

#### Given that Yuuno/Jupyter is up and running in your browser
1. Run Yuuno inside the unpaked Portable directory.
2. Run this code before enabling Yuuno:

        import sys
        sys.path.append(r"<PATH TO YOUR VAPOURSYNTH PORTABLE DIRECTORY>")

#### If the Server does not start up
Use the preferred way of running Yuuno:
1. Use `venv` (which comes preinstalled with your python installation)
2. Install (**inside a virtual env**) yuuno and vapoursynth-portable using this command: `pip install vapoursynth-portable yuuno`

Install plugins into the `<venv-path>/site-packages/plugins64` folder of your virtual environment.
In fact, this is the only way I officially support.

For more information, consult: https://docs.python.org/3/tutorial/venv.html

Fun fact: I use this method for developing Yuuno.

#### That being said:
Yuuno has a lot of transitive dependencies (around 30 other python packages; most come from Jupyter) to run correctly. To ensure you have them installed, you need to use `pip` which is a package manager that installs those packages for you.
