### ISSUE TITLE
Preview window not appearing

### ISSUE THREAD

**Issue by Zumochi** [Irrational-Encoding-Wizardry/yuuno#35]
* yuuno version: 1.2
* Python version: 3.8.2
* Operating System: Windows 10 x64

### Description

While everything seems to load properly, the preview window refuses to appear. That said, I am not sure if what I'm doing is correct.
What am I missing?

#### Terminal 1

```
cd yuuno-test
.\Scripts\Activate.ps1
jupyter notebook
```

Log:
```
(yuuno-test) E:\me\Videos\Encoding\yuuno-test> jupyter notebook
[I 14:56:30.591 NotebookApp] Serving notebooks from local directory: E:\me\Videos\Encoding\yuuno-test
[I 14:56:30.591 NotebookApp] The Jupyter Notebook is running at:
[I 14:56:30.592 NotebookApp] http://localhost:8888/?token=5927314598f905ab4b429cb6068b931c149ef45b75e8311f
[I 14:56:30.592 NotebookApp]  or http://127.0.0.1:8888/?token=5927314598f905ab4b429cb6068b931c149ef45b75e8311f
[I 14:56:30.592 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:56:30.735 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/me/AppData/Roaming/jupyter/runtime/nbserver-6636-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=5927314598f905ab4b429cb6068b931c149ef45b75e8311f
     or http://127.0.0.1:8888/?token=5927314598f905ab4b429cb6068b931c149ef45b75e8311f
```

#### Terminal 2

```
(yuuno-test) E:\me\Videos\Encoding\yuuno-test> ipython
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %load_ext yuuno

In [2]: test_clip = "../../Anime/ReLIFE/[FFF] ReLIFE - 01 [BD][1080p-FLAC][0FDEBF8A].mkv"

In [3]: %%vspreview
   ...: clip = core.ffms2.Source(test_clip)
   ...: clip.set_output()
   ...:
   ...:
Preview(clip=<vapoursynth.VideoNode object at 0x00000218C01B5310>)

In [4]: vs
Out[4]: <module 'vapoursynth' from 'e:\\me\\videos\\encoding\\yuuno-test\\lib\\site-packages\\vapoursynth.cp38-win_amd64.pyd'>

In [5]: core
Out[5]: <vapoursynth._CoreProxy at 0x218bea5fa30>
```

**Comment by stuxcrystal** [comment]
IPython runs in the terminal. Terminals cant show pictures so no preview is shown.

Did you try opening a notebook in the browser? A link to the webapplication is provided in the terminal where you entered `jupyter notebook`

**Comment by Zumochi** [comment]
Yes, I have Jupyter open in my browser, but I don't see anything happening there. I have zero experience with it though, so maybe I just need to navigate somewhere?

**Comment by stuxcrystal** [comment]
Can you try this.

This is fine. A notebook is a physical file on your filesystem. Therefore, you need to click on the button new on the tab "Files" like this:

![grafik](https://user-images.githubusercontent.com/2260352/79732883-94e6b480-82f4-11ea-896a-453ea832e297.png)

If you click on it, you get a new tab where you can enter "%load_ext yuuno"


Here is an example using my setup:
https://f.nemur.in/file/stux-sharex/ShareX/2020/04/2020-04-20_10-46-07.mp4

**Comment by Zumochi** [comment]
Thanks...! It seems I am blind and completely glossed over that part in the documentation. Maybe I need glasses 😄
