### ISSUE TITLE
Is there a way to zoom with pointresize?

### ISSUE THREAD

**Issue by Palladiawa** [Irrational-Encoding-Wizardry/yuuno#41]
I am trying to use yuuno to compare encodes. But since the image resizer works really fine, I cannot discover the artifacts at once. So I wonder if there is a way to resize the image using point resize, that can show the artifacts clearly.

the project works just fine, so I leave it empty below.

    * yuuno version:
    * Python version:
    * Operating System:

    ### Description

    Describe what you were trying to get done.
    Tell us what happened, what went wrong, and what you expected to happen.

    ### What I Did

**Comment by stuxcrystal** [comment]
The Zoom-feature inside the browser (the "100%" you see on the bottom-right corner) should be using NearestNeighbor.
